#! /bin/sh

if [ -z "$HOME" ]; then
	uid=`/opt/ts/gnu/bin/id -u`
	homedir="`getent passwd $uid | awk -F: '{print $6}'`"
else
	homedir="$HOME"
fi

if [ ! -f "$homedir/.environment" ]; then
	exit
fi

cat $homedir/.environment |
	egrep -v '^(#|$)' |
	while read line; do
		var=`echo "$line" | sed 's/^\([^=]*\)=.*$/\1/`
		value=`echo "$line" | sed 's/^[^=]*=\(.*\)$/\1/`
		echo "${var}=${value}; export $var;"
	done
